# Generated by Django 4.0.4 on 2022-06-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='created',
        ),
    ]
